# Generated by Django 5.2.4 on 2025-08-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chat', 'Chat'), ('bot', 'Bot'), ('room', 'Custom Room'), ('faq', 'FAQs'), ('help', 'Help Desk')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounts.group')),
            ],
        ),
    ]
