# Generated by Django 5.2.4 on 2025-10-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='name',
            field=models.CharField(choices=[('chat', 'Chat'), ('bot', 'Bot'), ('room', 'Custom Room'), ('faq', 'FAQs'), ('help', 'Help Desk')], max_length=50),
        ),
    ]
